testthat::expect_equal(replacena(1), 1)
testthat::expect_equal(replacena(1:10), 1:10)
testthat::expect_error(replacena(NA))
testthat::expect_error(replacena(c(NA, 1:10)))
testthat::expect_error(replacena(c(1:10, NA)))
testthat::expect_error(replacena(c(NA, 1:10, NA)))
testthat::expect_error(replacena(c(1, NA, NA, 1)))
testthat::expect_equal(replacena(c(3, NA, 3)), c(3, 3, 3))
testthat::expect_equal(replacena(c(2, -1, NA, 1)), c(2, -1, 0, 1))
testthat::expect_equal(replacena(c(Inf, NA, Inf)), c(Inf, Inf, Inf))