# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate a random permutation of a given numeric vector.
#' 
#' @param x numeric vector
#' @return permuted x
#' @examples
#' randperm(1:10)
#' letters[randperm(1:length(letters))]
#' randperm(iris$Species)
#' 
randperm <- function(x) {
    .Call('zero323_randperm', PACKAGE = 'zero323', x)
}

#' Generate a random, wihtout replacement,
#' subvector of length k of a given numeric vector x
#' 
#' @param x numeric vector
#' @param k number of elements
#' @return random subvector of x
#' @examples
#' sample2(1:100, 5)
#' sample2(runif(5, 0, 100), 3)
#' sample2(iris$Sepal.Length, 20)
#' 
sample2 <- function(x, k) {
    .Call('zero323_sample2', PACKAGE = 'zero323', x, k)
}

#' Merge two sorted (nondecreasingly or nonincreasingly) vectors
#' 
#' @param first numeric vector
#' @param second numeric vector
#' @return numeric vector
#' @examples
#' sortedmerge(c(1, 3, 5), c(2, 4, 6))
#' sortedmerge(3:1, 3:1)
#' 
sortedmerge <- function(first, second) {
    .Call('zero323_sortedmerge', PACKAGE = 'zero323', first, second)
}

